### ISSUE TITLE
It seems like youtubeinmp3 changed to convertmp3, but all the requests to their api returns error code 403:forbidden

### ISSUE THREAD

**Issue by Tomygames** [kvsjxd/YouMusix#2]
I don't have time trying to fix your code but I know the issue,
convertmp3 now checks your user agent, try faking it.
Doing that will help but will not fix it as, the API now allows direct downloads at a rate of 1 a day :/
Another solution was to get the video info with their API and get the mp3 link from their, but we get the same 1 day direct download thing.

**Comment by kvsjxd** [comment]
We cannot use convertmp3 in that case, unless we find a better service, I can't fix YouMusix

**Comment by interbiznw** [comment]
That is not what is giving the 403 error

**Comment by interbiznw** [comment]
This is the error

`java -jar YouMusix.jar
java.io.IOException: Server returned HTTP response code: 403 for URL: https://co                                        nvertmp3.io/fetch/?format=JSON&video=https://convertmp3.io/fetch/?video=https://                                        www.youtube.com/watch?v=HCjNJDNzw8Y
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown S                                        ource)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So                                        urce)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unkn                                        own Source)
        at java.net.URL.openStream(Unknown Source)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:1153)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:1140)
        at youmusix.Client$24$1.run(Client.java:490)
        at java.lang.Thread.run(Unknown Source)
`

**Comment by interbiznw** [comment]
the url is malformed

**Comment by interbiznw** [comment]
if you use this part of the url https://convertmp3.io/fetch/?video=https:// www.youtube.com/watch?v=HCjNJDNzw8Y

convertmp3.io works properly

**Comment by kvsjxd** [comment]
I made the changes but it's not working 🤔

**Comment by kvsjxd** [comment]
I have verified that this API is quite buggy and only works occasionally.
